# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9587a61c9d7381ac795b6fd35dcdb7e2f88628b3b19bfb40a871310b0a6fde2eaf34295bb75e1aaa4345ebf99f41bd9ee084e9680f74c80d0ea659fe0e2345c1

test:
  secret_key_base: 7823c4ed070a9793a084373d814e11f93fa2d02162f4199b0ca08765406ff3823f8807bed0ee1d64e4beb01b1de2cf6777d1ef0ba79dcecc69a4ab5b08de0032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
